Controllers/CadastroController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using plataformaordemdeservico.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using plataformaordemdeservico.Entidades;

namespace plataformaordemdeservico.Controllers
{
    public class CadastroController : Controller
    {

        private readonly Contexto db;

        public CadastroController(Contexto contexto)
        {
            db = contexto; 
        }


        // GET: CadastroController
        public IActionResult IndexCadastro()
        {
            //return View(lscadastro);
            return View();
        }

        // GET: CadastroController/Details/5
        public ActionResult Details()
        {
            return View();
        }

        // GET: CadastroController/Create
        public IActionResult CreateCadastro()
        {

            return View();
        }

        // POST: CadastroController/Create
        [HttpPost]
       
        public IActionResult CreateCadastro(CadastroDb cadastro)
        {
            //lscadastro.Add(cadastro);
            // return RedirectToAction("Ver pra onde vai voltar");
            db.DSCadastroCliente.Add(cadastro);
            db.SaveChanges();
            return RedirectToAction("Ver pra onde vai voltar");

        }


        // GET: CadastroController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: CadastroController/Edit/5
        [HttpPost]
        
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CadastroController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CadastroController/Delete/5
        [HttpPost]
       
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/CelularesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using plataformaordemdeservico.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using plataformaordemdeservico.Entidades;

namespace plataformaordemdeservico.Controllers
{
    public class CelularesController : Controller
    {
        private readonly Contexto db;

        public CelularesController(Contexto contexto)
        {
            db = contexto;
        }

        //public static List<Celulares> lscelulares = new List<Celulares>();

        // GET: CelularesController
        public IActionResult IndexCelulares()
        {
            return View();
        }

        // GET: CelularesController/Details/5
        public IActionResult Details(int id)
        {
            return View();
        }

        // GET: CelularesController/Create
        public IActionResult CreateCelulares()
        {
            return View();
        }

        // POST: CelularesController/Create
        [HttpPost]
        
        public IActionResult CreateCelulares(CelularesDb celulures)
        {
            db.DSCelulares.Add(celulures);
            return RedirectToAction("Ver pra onde vai voltar");
        }

        // GET: CelularesController/Edit/5
        public IActionResult Edit(int id)
        {
            return View();
        }

        // POST: CelularesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CelularesController/Delete/5
        public IActionResult Delete(int id)
        {
            return View();
        }

        // POST: CelularesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using plataformaordemdeservico.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace plataformaordemdeservico.Controllers
{
    public class LoginController : Controller
    {
        public static List<Login> lslogin = new List<Login>();

        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/NotebookController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using plataformaordemdeservico.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using plataformaordemdeservico.Entidades;

namespace plataformaordemdeservico.Controllers
{
    public class NotebookController : Controller
    {
        private readonly Contexto db;

        public NotebookController(Contexto contexto)
        {
            db = contexto;
        }

        //public static List<Notebook> lsnotebook = new List<Notebook>();

        // GET: NotebookController
        public ActionResult IndexNotebook()
        {
            return View();
        }

        // GET: NotebookController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: NotebookController/Create
        public ActionResult CreateNotebook()
        {
            return View();
        }

        // POST: NotebookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNotebook(NotebookDb notebook)
        {
            db.DSNotebook.Add(notebook);
            return RedirectToAction("Ver pra onde vai voltar");
        }

        // GET: NotebookController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: NotebookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NotebookController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: NotebookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="E:\Fatec\Projeto - Programacao WEB\plataformaordemdeserviço\plataformaordemdeservico\Views\style.css" />


</head>



<style>

    header {
        background-color: rgb(34 31 32);
        
        color: rgb(0,115,132);
        padding: 0;
    }

    .top-bar {

    }

    body {
        padding: 0;
        background-color: rgb(34 31 32);
        color: rgb(0,115,132);
        font-size: 30px;
        
    }
    h2 {
        text-align: center;
    }

    .text {
        color: rgb(0,115,132) !important;
        font-size: 30px;

    }

    .text-login {
        color: rgb(0,115,132) !important;
        font-size: 16px;
    }

    .box {
        background-color: rgb(34 31 32);
        color: rgb(0,115,132);
        text-align: center;
    }

    .box-login {
        position:absolute;
        right: 200px;
        margin-top: 0;
        font-size: 13px;
        display: table;
        
        
    }

    .footer-basic {
        padding: 40px 0;
        margin-top: 40px;
        position: initial;
        left: 0;
        bottom: 0;
        width: 100%;
        background-color: rgb(34 31 32);
        color: rgb(0,115,132);
    }

        .footer-basic ul {
            padding: 0;
            list-style: none;
            text-align: center;
            font-size: 18px;
            line-height: 1.6;
            margin-bottom: 0;
        }

        .footer-basic li {
            padding: 0 10px;
        }

        .footer-basic ul a {
            color: inherit;
            text-decoration: none;
            opacity: 0.8;
        }

            .footer-basic ul a:hover {
                opacity: 1;
            }

        .footer-basic .social {
            text-align: center;
            padding-bottom: 25px;
        }

            .footer-basic .social > a {
                font-size: 24px;
                width: 40px;
                height: 40px;
                line-height: 40px;
                display: inline-block;
                text-align: center;
                border-radius: 50%;
                /*border: 1px solid #ccc;*/
                margin: 0 8px;
                color: inherit;
                opacity: 0.75;
            }

                .footer-basic .social > a:hover {
                    opacity: 0.9;
                }

        .footer-basic .copyright {
            margin-top: 15px;
            text-align: center;
            font-size: 13px;
            color: rgb(0,115,132);
            margin-bottom: 0;
        }


</style>


<body>

    
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm mb-3 ">

            <div class="box-login navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-0">
                    <li class="nav-item">
                        <a class="nav-link text-login" asp-area="" asp-controller="Cadastro" asp-action="CreateCadastro">Cadastre-se</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-login" asp-area="" asp-controller="Login" asp-action="Index">Entrar</a>
                    </li>
                </ul>
            </div>
            <img src="~/images/SD-INFORMÁTICA_logotipo.png" width="200" height="160" />

            <div class="container">
                @*<a class="navbar-brand"  asp-area="" asp-controller="Home" asp-action="Index"></a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="true" s aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="Notebook" asp-action="CreateNotebook">Notebook</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="Computadores" asp-action="CreateComputadores">Computadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="Monitores" asp-action="CreateMonitores">Monitores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="Impressoras" asp-action="CreateImpressoras">Impressoras</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text" asp-area="" asp-controller="Celulares" asp-action="CreateCelulares">Celulares</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">

            @RenderBody()

        </main>
    </div>




    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>