Models/Notebook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace plataformaordemdeservico.Models
{
    public class Notebook
    {
        public int cod_note { get; set; }
        public string modelo_note { get; set; }
        public string fabricante { get; set; }
        public string serie_note { get; set; }
        public string polegadas { get; set; }
        //se carregador original
        public string carregador { get; set; }
        public string descricao_note { get; set; }
        public string anexo_note { get; set; }
        public int status { get; set; }
        public DateTime data { get; set; }

        public int protocolo { get; set; }

    }
}

Controllers/FaleConoscoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using plataformaordemdeservico.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using plataformaordemdeservico.Entidades;

namespace plataformaordemdeservico.Controllers
{
    public class FaleConoscoController : Controller
    {

        private readonly Contexto db;

        public FaleConoscoController(Contexto contexto)
        {
            db = contexto;
        }

        //public static List<FaleConosco> lsfaleconosco = new List<FaleConosco>();

        // GET: FaleConoscoController
        public ActionResult IndexFaleConosco()
        {
            return View();
        }

        // GET: FaleConoscoController/Details/5
        public ActionResult Details()
        {
            return View();
        }

        // GET: FaleConoscoController/Create
        public ActionResult CreateFaleConosco()
        {
            return View();
        }

        // POST: FaleConoscoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateFaleConosco(FaleConoscoDb faleConosco)
        {
            db.DSFaleConosco.Add(faleConosco);
            return RedirectToAction("Ver pra onde vai voltar");

        }

        // GET: FaleConoscoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FaleConoscoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FaleConoscoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FaleConoscoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/NotebookController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using plataformaordemdeservico.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using plataformaordemdeservico.Entidades;

namespace plataformaordemdeservico.Controllers
{
    public class NotebookController : Controller
    {
        private readonly Contexto db;

        public NotebookController(Contexto contexto)
        {
            db = contexto;
        }

        //public static List<Notebook> lsnotebook = new List<Notebook>();

        // GET: NotebookController
        public ActionResult IndexNotebook()
        {
            return View();
        }

        // GET: NotebookController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: NotebookController/Create
        public ActionResult CreateNotebook()
        {
            return View();
        }

        // POST: NotebookController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateNotebook(NotebookDb notebook)
        {
            db.DSNotebook.Add(notebook);
            return RedirectToAction("Ver pra onde vai voltar");
        }

        // GET: NotebookController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: NotebookController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: NotebookController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: NotebookController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Notebook/CreateNotebook.cshtml
@model plataformaordemdeservico.Models.Notebook

@{
    ViewData["Title"] = "CreateNotebook";
}

</br>

<h2>Solicitação de Reparo - Notebook</h2>

</br></br>
<hr />

<style>

   

    .text-bnt {
        color: rgb(0,115,132);
        font-size: 16px;
    }

    .btn-save {
        background-color: rgb(34 31 32); /* Green */
        border: solid rgb(0,115,132);
        color: rgb(0,115,132);
        padding: 15px 32px;
        text-align: center;
        text-decoration: solid;
        display: inline-block;
        font-size: 16px;
    }
</style>

<div class="row">
    <div class="col-md-6 text-bnt content">
        <form asp-action="CreateNotebook">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                    <label asp-for="cod_note" class="control-label"></label>
                    <input asp-for="cod_note" class="form-control" />
                    <span asp-validation-for="cod_note" class="text-danger"></span>
                </div>*@
            <div class="form-group">
                <label asp-for="modelo_note" class="control-label">Modelo:</label>
                <input asp-for="modelo_note" class="form-control" />
                <span asp-validation-for="modelo_note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fabricante" class="control-label">Fabricante:</label>
                <input asp-for="fabricante" class="form-control" />
                <span asp-validation-for="fabricante" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="serie_note" class="control-label">Nº Série:</label>
                <input asp-for="serie_note" class="form-control" />
                <span asp-validation-for="serie_note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="polegadas" class="control-label">Polegadas:</label>
                <input asp-for="polegadas" class="form-control" />
                <span asp-validation-for="polegadas" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="carregador" class="control-label">Possui carregador:</label>
                <input asp-for="carregador" class="form-control" />
                <span asp-validation-for="carregador" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descricao_note" class="control-label">Descrição do problema:</label>
                <input asp-for="descricao_note" class="form-control" />
                <span asp-validation-for="descricao_note" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="anexo_note" class="control-label">anexo</label>
                <input asp-for="anexo_note" class="form-control" />
                <span asp-validation-for="anexo_note" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                    <label asp-for="status" class="control-label"></label>
                    <input asp-for="status" class="form-control" />
                    <span asp-validation-for="status" class="text-danger"></span>
                </div>*@
            @*<div class="form-group">
                    <label asp-for="data" class="control-label"></label>
                    <input asp-for="data" class="form-control" />
                    <span asp-validation-for="data" class="text-danger"></span>
                </div>*@

            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-secondary btn-save text-bnt" />
            </div>
        </form>
    </div>
</div>


<div class="footer-basic">
    <footer>
        <div class="social">
            <ul class="list-inline">
                <li class="list-inline-item"><a class="nav-link text" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a></li>
                <li class="list-inline-item"><a class="nav-link text" asp-area="" asp-controller="Home" asp-action="SobreNos">Sobre nós</a></li>
                <li class="list-inline-item"><a class="nav-link text" asp-area="" asp-controller="FaleConosco" asp-action="CreateFaleConosco">Fale Conosco</a></li>
            </ul>
            <br />
            <a href="https://www.linkedin.com/feed/?trk=BR-SEM_google-adwords_Jordan-brand-sign-up"> <img src="~/images/linkedid.png" /> <i class="icon ion-social-snapchat"> </i></a>
            <a href="https://www.facebook.com/"><i class="icon ion-social-twitter"> <img src="~/images/facebook.png"> </i></a>
            <a href="https://www.instagram.com/"><i class="icon ion-social-facebook"> <img src="~/images/insta.png"> </i></a>
            <a href="https://www.whatsapp.com/?lang=pt_br"> <i class="icon ion-social-linked"> <img src="~/images/Whatsapp.png"> </i> </a>
        </div>

        <p class="copyright">SD - INFORMATICA © 2022</p>
    </footer>
</div>



@*<div>
        <a asp-action="Index">Back to List</a>
    </div>*@

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Notebook/IndexNotebook.cshtml
@model IEnumerable<plataformaordemdeservico.Models.Notebook>

@{
    ViewData["Title"] = "IndexNotebook";
}

<h1>IndexNotebook</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.cod_note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.modelo_note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.fabricante)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.serie_note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.polegadas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.carregador)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.descricao_note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.anexo_note)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.data)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.cod_note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.modelo_note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fabricante)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.serie_note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.polegadas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.carregador)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descricao_note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.anexo_note)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.data)
            </td>
            
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>